# Default values for petclinic.

replicaCount: 1

image:
  repository: ykravchenkodh/petclinic
  tag: armPetclinic
  pullPolicy: Always

service:
  type: LoadBalancer
  containerPort: 8080

resources:
  requests:
    memory: "256Mi"


postgresql:
  enabled: false
  auth:
    username: petclinic
    database: petclinic

mysql:
  enabled: false
  auth:
    username: petclinic
    database: petclinic


